-- 004_create_destinations.sql
-- Create destinations table with PostGIS geography point and Google Place metadata

CREATE TABLE IF NOT EXISTS destinations (
  id INTEGER PRIMARY KEY,
  place_id VARCHAR(255) UNIQUE,
  state_id VARCHAR(100) REFERENCES states(id),
  state_name VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255),
  location VARCHAR(255) NOT NULL,
  district VARCHAR(255),
  region VARCHAR(50) NOT NULL,
  category VARCHAR(100) NOT NULL,
  difficulty VARCHAR(50) DEFAULT 'Easy',
  description TEXT,
  short_description TEXT,
  price_per_person NUMERIC(12, 2) DEFAULT 0,
  budget_min NUMERIC(12, 2) DEFAULT 0,
  budget_max NUMERIC(12, 2) DEFAULT 0,
  rating NUMERIC(3, 2) DEFAULT 4.5,
  review_count INTEGER DEFAULT 0,
  duration VARCHAR(100),
  ideal_duration VARCHAR(100),
  best_season VARCHAR(255),
  best_time_to_visit VARCHAR(255),
  best_time VARCHAR(255),
  climate VARCHAR(100),
  featured BOOLEAN DEFAULT FALSE,
  popular BOOLEAN DEFAULT FALSE,
  tags TEXT[],
  highlights TEXT[],
  attractions TEXT[],
  activities TEXT[],
  how_to_reach JSONB,
  travel_tips TEXT[],
  coordinates JSONB,
  geo_location geography(Point, 4326),
  google_place_id VARCHAR(255),
  google_rating NUMERIC(3, 2),
  google_user_rating_count INTEGER,
  google_maps_uri TEXT,
  formatted_address TEXT,
  search_query VARCHAR(255),
  image TEXT,
  hero_image TEXT,
  thumbnail_url TEXT,
  gallery TEXT[],
  place_photos JSONB,
  image_status VARCHAR(50) DEFAULT 'verified',
  image_source VARCHAR(100) DEFAULT 'Wikimedia Commons',
  image_license VARCHAR(100) DEFAULT 'CC BY-SA 4.0',
  image_attribution TEXT,
  image_author VARCHAR(255),
  source_url TEXT,
  image_metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
